### ISSUE TITLE
Input api key via stdin

### ISSUE THREAD

**Issue by alexellis** [civo/cli#101]
I'd like to be able to input the api key via stdin, not just via an argument to the command.

Why? It exposes a confidential token in my bash history and could leak or be sent back by analytics tools or exposed on a live stream when finding past commands.

OpenFaaS' CLI enables the use of a file i.e. `cat password | faas-cli login` or `echo $PASSWORD | faas-cli login`

You're welcome to copy the code / approach that we use in the login command.

I'd feel more comfortable using the Civo CLI if this change was made to increase security.

https://github.com/openfaas/faas-cli/blob/master/commands/login.go

**Comment by andyjeffries** [comment]
Good suggestion but there's nothing wrong with using $PASSWORD (or $API_KEY) with the Civo CLI instead of the raw API key too. I do think asking for it interactively if not supplied as a parameter is a good idea though.

**Comment by andyjeffries** [comment]
@RealHarshThakur this might be a nice easy one to get you in to the CLI codebase.

**Comment by RealHarshThakur** [comment]
Added this feature, so closing this. :)
