### ISSUE TITLE
Add support for passing CIVO_TOKEN

### ISSUE THREAD

**Issue by solidnerd** [civo/cli#107]
For more convenience, it would be cool to be able also to set the API key and region via an environment variable. This would allow it easier to use in CI Systems for example GitLab CI.

Currently, I use a short workaround like this:

```shell
 civo apikey add civo-k3s $CIVO_TOKEN
 civo apikey current civo-k3s
 civo kubernetes config $(cat terraform/civo-cloud/CLUSTER_NAME) --save --merge
```
 I found that the terraform provider already supports this behavior. I think it would be also a great extension to the CLI.

**Comment by zulh-civo** [comment]
Adding this [conversation](https://civo-community.slack.com/archives/CMVCKMCN5/p1630122409060900) from Civo community Slack channel for reference.

<img width="623" alt="Screenshot 2021-09-29 at 12 05 21 PM" src="https://user-images.githubusercontent.com/75463191/135201553-4eb27ad0-ebaf-4989-9eeb-585b19f27f52.png">

**Comment by zulh-civo** [comment]
I'm going to scope down this issue to just for setting API key via environment variable as I couldn't tell how `CIVO_REGION` could be used/useful if we support it. The workaround provided at the top only hints for `CIVO_TOKEN`.

Assumming `CIVO_REGION` was set earlier, switching to it would be just running a single command.

Something like this:

```
# set the environment variable
$ export CIVO_REGION=LON1

# set the region
$ civo region current $CIVO_REGION
The default region was set to (London 1) LON1

# or
$ civo region set $CIVO_REGION
The default region was set to (London 1) LON1
```

I'm happy to be corrected here. Feel free to open a new issue for CIVO_REGION and include your proposal (the steps, commands and flags that you wish available).

**Comment by zulh-civo** [comment]
I'm going to create a PR for this #107 issue.

When it's merged and released, it will support this flow:

```
$ export CIVO_API_KEY_NAME=personal
$ export CIVO_API_KEY=<CIVO-API-KEY>
$ civo apikey save --load-from-env
```

Which in turns will create/update _~/.civo.json_ file to:

```json
{
  "apikeys": {
    "personal": "<CIVO-API-KEY>"
  },
  "meta": {
    "admin": false,
    "current_apikey": "personal",
    "default_region": "FRA1",
    "latest_release_check": "2021-09-29T12:45:35+08:00",
    "url": "https://api.civo.com"
  }
}
```
