### ISSUE TITLE
InternalServerError when creating a cluster with app that has plans

### ISSUE THREAD

**Issue by zulh-civo** [civo/cli#122]
I just noticed this error today where I got `InternalServerError` message when I created a cluster with app that has plans. When I checked in Civo.com, the cluster was created successfully. But there was no apps under the _Installed Applications_ tab.

```
$ civo k8s create mariadb -a=MariaDB # <-- has plans
Error: InternalServerError: internal Server Error

$ civo k8s create gitea -a=gitea # <-- has no plans
The cluster gitea (e6996d3c-3a0c-450a-93b0-9bb2411063e7) has been created
```

**UPDATE**

This is being tracked internally at Civo (for Civo staff):

- issue 13 in civo/api
- issue 58 in civo/api-go

**Comment by zulh-civo** [comment]
Seems like this is API-related:

![Screenshot 2021-08-24 at 3 53 27 PM](https://user-images.githubusercontent.com/75463191/130578921-5e985e5d-fd7f-460a-ae04-ec20653889c3.png)

FYI @kaihoffman @tahsin352

**Comment by zulh-civo** [comment]
I checked this again today. The API server now returns an error when:

- no plan is provided
- a plan is provided, but invalid

But, the cluster still get created even though there was request validation error. Strange. @kaihoffman 

![Screenshot 2021-09-28 at 2 52 08 PM](https://user-images.githubusercontent.com/75463191/135037926-0d404e03-6d0b-4d8a-ada0-ac0a0eb468b8.png)

I'll try to see what I can do to prevent this from happening. At least, from CLI standpoint.

**Comment by zulh-civo** [comment]
I had a chat with @andyjeffries about this just now and we agreed not to fix this on CLI side. Instead, it will be fixed in API side. I'm going to keep this issue opened for tracking purpose. Once API side is patched, I'll retest this.

**Comment by haardikdharma10** [comment]
@zulh-civo, this was fixed in civo/api-go and issue 58 seems to be closed a while ago. Can you retest this and confirm if this is fixed so that we can close this issue.

**Comment by zulh-civo** [comment]
I can confirm it's working as expected now

![Screenshot 2022-03-15 at 9 11 45 AM](https://user-images.githubusercontent.com/75463191/158286478-eade0c92-6f07-44dd-9d1b-203c8305a281.png)
