### ISSUE TITLE
Support for creating clusters without default apps like traefik

### ISSUE THREAD

**Issue by ghost** [civo/cli#13]
In order to create a cluster without the default ingress controller traefik, a command line switch like `--remove-applications=traefik` or `--without-ingress` would be helpful, especially in cases where I would like to use a different ingress controller. Currently, this is possible through the web interface by deselecting a default app (traefik or metrics-server).

Should civo decide to bundle more applications into the default cluster creation step, such a flag would give the developer more control over the creation process.

Alternatively, a more inclusive approach would work as well like `--with-application=none` defaulting to `--with-application=traefik,metrics-server`.

**Comment by alejandrojnm** [comment]
@andyjeffries i will add `--applications` and `--remove-applications` like the old cli, are you ok with that?
You can use both at the same time, so you can say `--applications=haproxy --remove-applications=Traefik,metrics-server`

**Comment by andyjeffries** [comment]
Absolutely, any bits that the old CLI supported and the new one doesn't should be added.

**Comment by alejandrojnm** [comment]
Close this in d94a61c
