### ISSUE TITLE
Instance reboot not working 

### ISSUE THREAD

**Issue by saiyam1814** [civo/cli#136]
```
civo instance create --hostname=api-demo.test --size g3.small --diskimage=12745392-15c7-4140-925d-441fe7ae57fd --initialuser=demo-user
The instance api-demo.test has been created

civo instance reboot api-demo.test
Error: DatabaseInstanceNotFoundError: Failed to find the instance in the internal database
```

**Comment by zulh-civo** [comment]
This is an upstream issue (see link above) and the fixes will be done in civogo first before I can come back here to fix the calling method.

**Comment by zulh-civo** [comment]
PR sent (see link above). No change is needed in the CLI code. I just bumped the civogo library version to the [latest](https://github.com/civo/civogo/releases/tag/v0.2.54) one (which contains the actual fix).
