### ISSUE TITLE
Show number of clusters using a firewall in `civo firewalls ls`

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#161]
Currently, the firewall listing for a particular region has fields for the ID, Name, Network, total rules in that firewall, and total instances using that firewall:

```console
$ civo firewall ls
+--------------------------------------+-----------------------------------+---------+-------------+-----------------+
| ID                                   | Name                              | Network | Total rules | Total Instances |
+--------------------------------------+-----------------------------------+---------+-------------+-----------------+
| 16a4e13a-e228-4cba-8630-505c7cdf5ca7 | Default (all open)                | Default |           3 |               0 |
| 2cea9b25-4792-4e27-94a6-de15bd186273 | Kubernetes cluster: test123       | Default |           2 |               0 |
+--------------------------------------+-----------------------------------+---------+-------------+-----------------+
```

It would be good to also show "Total Clusters" as a column, because it looks really odd that a firewall for a Kubernetes cluster shows as 0 instances using it (despite it being used by a cluster).

So the output could be:

```console
$ civo firewall ls
+--------------------------------------+-----------------------------------+---------+-------------+-----------------+----------------+
| ID                                   | Name                              | Network | Total rules | Total Instances | Total Clusters |
+--------------------------------------+-----------------------------------+---------+-------------+-----------------+----------------+
| 16a4e13a-e228-4cba-8630-505c7cdf5ca7 | Default (all open)                | Default |           3 |               0 |              0 |
| 2cea9b25-4792-4e27-94a6-de15bd186273 | Kubernetes cluster: test123       | Default |           2 |               0 |              1 |
+--------------------------------------+-----------------------------------+---------+-------------+-----------------+----------------+
```

**Comment by avinashupadhya99** [comment]
Would this require a change in the API or is there a better way to do it since the https://www.civo.com/api/firewall API does not return any information about the clusters using the firewall?

**Comment by kaihoffman** [comment]
@avinashupadhya99 I suspect it could be done the same way the instance numbers using a particular firewall are retrieved.

**Comment by avinashupadhya99** [comment]
The instance numbers are returned by the API https://api.civo.com/v2/firewalls so the API might have to be modified to return the cluster count as well.

**Comment by zulh-civo** [comment]
Here is the high level flow when someone runs `civo firewalls ls` command now:

1. It creates a client and [hit](https://github.com/civo/cli/blob/452cda371dbe9c21d3a968bbfab21e3c7cdf1192/cmd/firewall_list.go#L39) `ListFirewalls` method in civogo
2. In civogo, the `ListFirewalls` method [calls](https://github.com/civo/civogo/blob/9c0fe17f32dfc5000c65154b84b339125934260e/firewall.go#L59-L71) [GET] `/v2/firewalls` API endpoint
3. When the request ends, it will return the API response in form of [`Firewall`](https://github.com/civo/civogo/blob/9c0fe17f32dfc5000c65154b84b339125934260e/firewall.go#L11-L17) array (array of structs to be specific)
4. In that `Firewall` struct, there's a [field](https://github.com/civo/civogo/blob/9c0fe17f32dfc5000c65154b84b339125934260e/firewall.go#L15) called `InstancesCount`, which is a Go type representation for the `instances_count` field from the API JSON response. Here is the response sample (taken from API docs, as of Nov 1, 2021):
    ```
    [
      {
        "id": "cde686be-6fbd-48e8-9777-83d805853235",
        "name": "Default (all open)",
        "account_id": "433e075e-37ac-4533-8b74-4a6d7337b394",
        "rules_count": 3,
        "instances_count": null,
        "default": "true",
        "label": null,
        "network_id": "5c16ab17-933a-46ed-96c6-8a093a0179e1"
      },
      {
        "id": "af5f3bae-38f7-496c-9561-283ae1349915",
        "name": "test",
        "account_id": "433e075e-37ac-4533-8b74-4a6d7337b394",
        "rules_count": 0,
        "instances_count": null,
        "default": "false",
        "label": null,
        "network_id": "5c16ab17-933a-46ed-96c6-8a093a0179e1"
      }
    ]
    ```
5. So when CLI gets the response back (via civogo above), it [prints](https://github.com/civo/cli/blob/452cda371dbe9c21d3a968bbfab21e3c7cdf1192/cmd/firewall_list.go#L55) the column by accessing that `InstancesCount` field in the `Firewall` struct

I'd say this issue depends on the Civo API. Once we add a new field for `ClustersCount`, then we can make progress with this issue. I'm going to file an issue in Civo internal issues tracker for this one.

**Comment by zulh-civo** [comment]
FYI, this is tracked internally at Civo (for Civo staff: as issue 102 in civo/api-go)

**Comment by zulh-civo** [comment]
@alejandrojnm do you mind writing some notes about this? Fixed? Ignored?

**Comment by alejandrojnm** [comment]
Yes we modify the API to get that info from our backend
