### ISSUE TITLE
--create-firewall errors if argument not provided

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#185]
I just tried to create a cluster with the CLI with
```
civo k8s create demo --create-firewall --wait
```
and it just returned an error `Error: flag needs an argument: --create-firewall`.

However, the help text says:
> -c, --create-firewall string       optional, semicolon-separated list of ports to open - leave blank for default (80;443;6443) or you can use "all"

I'm on CLI version v.1.0.14

It makes no difference if `--create-firewall` is the last argument or not.

**Comment by alejandrojnm** [comment]
Possible fix in this PR https://github.com/civo/cli/pull/187

**Comment by haardikdharma10** [comment]
@alejandrojnm if this is fixed, we can close this issue.

**Comment by haardikdharma10** [comment]
Verified that this is not an issue in the latest CLI version. Closing. @kaihoffman feel free to reopen if you are able to reproduce it again 😄
