### ISSUE TITLE
CIVO CLI keeps giving database_region_not_found

### ISSUE THREAD

**Issue by rjvim** [civo/cli#192]
`civo version`

Civo CLI v1.0.22

`civo region ls`

Error: Error: Unknown error response - status: 404 Not Found, code: 404, reason: {"code":"database_region_not_found","reason":"Failed to find the region within the internal database"}

I have tried with both installing CLI and with Docker.

`civo k8s applications ls --region=LON1`

Error: Error: Unknown error response - status: 404 Not Found, code: 404, reason: {"code":"database_region_not_found","reason":"Failed to find the region within the internal database"}

I am following this: https://www.civo.com/docs/cli/633

Some commands do work like `civo k8s ls --region=LON1`

**Comment by alejandrojnm** [comment]
Can you try `civo update`

**Comment by haardikdharma10** [comment]
@alejandrojnm is this fixed?

**Comment by alejandrojnm** [comment]
I think yes

**Comment by haardikdharma10** [comment]
Tested and verified that the bug is fixed in v1.0.23
@rjvim can you please update the cli and confirm if it is fixed for you too so that I can close the issue? 😄

**Comment by rjvim** [comment]
@haardikdharma10 I can confirm this is working in latest CLI.

The issue was: https://www.civo.com/docs/cli/617

As a newbie to Civo, I would be starting at the Docs section of your website and following those steps. And it's outdated in the blog. You can close this because it's working in the latest version, but the actual closure would be when it's updated in the documentation too, please.

**Comment by haardikdharma10** [comment]
Thanks for the feedback @rjvim. However, the link you have mentioned above links to "Setting up Civo CLI" which doesn't look outdated to me. Can you help specify exactly which parts of the documentation you feel are incomplete/outdated?

**Comment by rjvim** [comment]
@haardikdharma10 

<img width="1078" alt="Screenshot 2022-03-14 at 6 30 29 PM" src="https://user-images.githubusercontent.com/23579455/158177036-f55e997e-502a-4d86-96dc-f8097ed6cea6.png">

Above is the screenshot of instructions which suggest:

`wget https://github.com/civo/cli/releases/download/v0.7.6/civo-0.7.6-linux-amd64.tar.gz`

Is 0.7.6 the one should be installing? or 1.0.23 which is here: [v1.0.23](https://github.com/civo/cli/releases/tag/v1.0.23)

You can update the document with:

`wget https://github.com/civo/cli/releases/download/v1.0.23/civo-1.0.23-linux-arm64.tar.gz`

**Comment by haardikdharma10** [comment]
Awesome, thanks @rjvim. @kunal-kushwaha probably something for you to take a look at once you're back 😄

**Comment by mryan1** [comment]
I had this issue and had to manually edit ` ~/.civo.json ` as ` civo region current ` didn't appear to update it properly.

**Comment by kunal-kushwaha** [comment]
> @haardikdharma10
> 
> <img alt="Screenshot 2022-03-14 at 6 30 29 PM" width="1078" src="https://user-images.githubusercontent.com/23579455/158177036-f55e997e-502a-4d86-96dc-f8097ed6cea6.png">
> 
> Above is the screenshot of instructions which suggest:
> 
> `wget https://github.com/civo/cli/releases/download/v0.7.6/civo-0.7.6-linux-amd64.tar.gz`
> 
> Is 0.7.6 the one should be installing? or 1.0.23 which is here: [v1.0.23](https://github.com/civo/cli/releases/tag/v1.0.23)
> 
> You can update the document with:
> 
> `wget https://github.com/civo/cli/releases/download/v1.0.23/civo-1.0.23-linux-arm64.tar.gz`

Done!

**Comment by haardikdharma10** [comment]
@kunal-kushwaha thanks for updating the doc. Do we have any way to make it future-proof? Currently, we are just hard-coding the cli version in the command. CLI version is updated frequently and hence it is next to impossible to update the page every time we release a new cli version (For example, we are on version 1.0.25 currently, so the command is already outdated). @kaihoffman any idea how do we go about it?

**Comment by kaihoffman** [comment]
Either we would need to specify a command or a link to find the appropriate version and indicate to use that in the `wget` code sample, or we would need to be able to specify a permanent link that would serve the latest stable release?

**Comment by OldManFroggy** [comment]
confirmed, new 1.0.25 install on linux amd64 -> sets region incorrectly when apikey is added

Had to edit ~/.civo.json and set region to a valid region LON1, FRA1, or NYC1 in my case, initially it was set to 'SYB1' I think, I forgot to write it down.

**Comment by OldManFroggy** [comment]
> @kunal-kushwaha thanks for updating the doc. Do we have any way to make it future-proof? Currently, we are just hard-coding the cli version in the command. CLI version is updated frequently and hence it is next to impossible to update the page every time we release a new cli version (For example, we are on version 1.0.25 currently, so the command is already outdated). @kaihoffman any idea how do we go about it?

I would suggest a 'current' or 'latest' build version  then documents will not need changing on each new release.

**Comment by alejandrojnm** [comment]
@kunal-kushwaha we can put 'current' or 'latest' as suggest @scott-ling

**Comment by kaihoffman** [comment]
I'm reviewing the docs anyway, and am looking at pointing users to the shell script at `curl -sL https://civo.com/get | sh` as a primary way to install @alejandrojnm
