### ISSUE TITLE
Initialisation script

### ISSUE THREAD

**Issue by stiliajohny** [civo/cli#210]
On the Web front-end there is an option to initialise the instance with a script 
however, on the civo cli this option doesn't exist

is there any plan to add this ?

![image](https://user-images.githubusercontent.com/17669235/159127081-0af85be0-c814-438c-997f-6c3c9a384280.png)

**Comment by haardikdharma10** [comment]
Thanks for the feedback @stiliajohny. I will confirm with the team internally whether why this was left out as a flag with `civo instance create`. I believe there might be some valid reason to leave it out. @alejandrojnm anything we are aware of or can we just add it as a flag?

**Comment by ghost** [comment]
This should probably just be a flag named `--user-script` that takes a path to a file. If for any reason a user would want to have their user-script come from stdin or as part of some one-liner, there are plenty of creative ways to do that.

Looks to me like when the flag is specified, the file should contents should be read into [InstanceConfig.Script](https://pkg.go.dev/github.com/civo/civogo#InstanceConfig).

**Comment by stiliajohny** [comment]
> This should probably just be a flag named `--user-script` that takes a path to a file. If for any reason a user would want to have their user-script come from stdin or as part of some one-liner, there are plenty of creative ways to do that.
> 
> Looks to me like when the flag is specified, the file should content should be read into [InstanceConfig.Script](https://pkg.go.dev/github.com/civo/civogo#InstanceConfig).

Thank you @protosam 
Shall we expect this flag to be added soon, any plans? 

Thanks in advance!

**Comment by ghost** [comment]
If this is still open later this week, I'll likely make a PR with the change. Otherwise, the PR will be next week.

**Comment by stiliajohny** [comment]
Legend. Thanks a lot for the quick turn around

**Comment by ghost** [comment]
We can close this issue now.

**Comment by stiliajohny** [comment]
Closed as per #218 :rocket:
