### ISSUE TITLE
CLI shows duplicate output on invalid command

### ISSUE THREAD

**Issue by kunal-kushwaha** [civo/cli#213]
When you input an invalid command, the Civo CLI shows the same message twice.

```
$ civo xyz
Error: unknown command "xyz" for "civo"
Run 'civo --help' for usage.
unknown command "xyz" for "civo"
```

**Comment by haardikdharma10** [comment]
@kunal-kushwaha not sure what version of CLI you're on? On the latest CLI `1.0.25`, I don't see this as an issue - 

```
$ civo xyz
Error: unknown command "xyz" for "civo"
Run 'civo --help' for usage.
```

Can you check `civo version` and update? If the issue still persists, I would be happy to look into it further 😄

**Comment by kunal-kushwaha** [comment]
Oh yes you are right, lgtm
