### ISSUE TITLE
`civo kubernetes ls` command is not working

### ISSUE THREAD

**Issue by khabdrick** [civo/cli#214]
![2022-04-03_13-14](https://user-images.githubusercontent.com/57852546/161427584-2c523b7d-a9e9-4833-9a40-ee1c5a335715.png)

**Comment by haardikdharma10** [comment]
Hi @khabdrick, can you check your Civo version by running `civo version`. If it is not already updated, please try updating it with `civo update` and check if the issue still persists? 😄

**Comment by khabdrick** [comment]
![2022-04-04_13-34](https://user-images.githubusercontent.com/57852546/161544647-54c12f14-33ac-41e3-b1ed-53e5f3cdcde7.png)
I am having a new error. I actually added region when creating the cluster.
