### ISSUE TITLE
instance creation `--tags` not respected

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#242]
Using version v1.0.32

Instance creation documentation states

```
  -g, --tags string          the instance's tags
```

Using either `-g demo` or `--tags demo`/ `--tags=demo` does not get passed to the instance, meaning that instances are not created with the provided tags.

**Comment by haardikdharma10** [comment]
@kaihoffman this should be fixed with - https://github.com/civo/cli/pull/243
