### ISSUE TITLE
Default parameters in the CLI maybe aren't working

### ISSUE THREAD

**Issue by andyjeffries** [civo/cli#273]
```
$ civo firewall rule create $firewall_id -o json --region=LON1 -c "1.2.3.4/32" -s 6443 -e 6443 -l "github-runner" | jq
Error: required flag(s) "action", "direction" not set
Usage:
  civo firewall rule create [flags]

Aliases:
  create, new, add

Examples:
civo firewall rule create FIREWALL_NAME/FIREWALL_ID [flags]

Flags:
  -a, --action string      the action of the rule can be allow or deny (default is allow) (default "allow")
  -c, --cidr string        the CIDR of the rule you can use (e.g. -c 10.10.10.1/32,148.2.6.120/32) (default "0.0.0.0/0")
  -d, --direction string   the direction of the rule can be ingress or egress (default is ingress) (default "ingress")
```

Notice how I didn't give an action or a direction, the CLI failed, even though a default is specified for both (and indeed two defaults the same are given for `action`).

**Comment by alessandroargentieri** [comment]
hello, @andyjeffries could you please show the CLI version you're using?

**Comment by vishalanarase** [comment]
@andyjeffries Which CLI version are you using?

I'm not able to reproduce the issue with latest CLI version  v1.0.40
```bash
$ civo firewall rule create 218dc85a-f318-42e9-9b5f-529196641d47  -c "1.2.3.4/32" -s 6443 -e 6443 -l "github-runner"
Created a firewall rule called github-runner to allow, ingress access to port 6443 from 1.2.3.4/32 with ID 06fb2bb2-d57b-4cfd-ac82-a2d869ab6a5d
```

**Comment by andyjeffries** [comment]
Good question, maybe it was an old version at the time, and I've since updated...

**Comment by haardikdharma10** [comment]
@andyjeffries I believe this was fixed with - https://github.com/civo/cli/pull/255 Can you confirm if this is not the issue on the latest version? If so, we can close this issue :)

**Comment by andyjeffries** [comment]
Yeah, it works on latest version so we can close this. The old CLI (before Go) used to warn you if you weren't running the latest version by checking GitHub public releases API, might be worth bringing that back...

**Comment by vishalanarase** [comment]
We have added support to warn user https://github.com/civo/cli/pull/252 Your suggestion was in place
