### ISSUE TITLE
`civo ip rm` not aliased to `delete`

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#277]
Other resources such as instances and clusters can be deleted with an aliased `civo rm resourcetype` command. It seems reserved IP deletion is not aliased the same way and only accepts `delete`.

**Comment by alessandroargentieri** [comment]
@kaihoffman why the "invalid" label?

**Comment by kaihoffman** [comment]
@alessandroargentieri I was vacillating between it and "bug" but given the description is "this doesn't seem right" I took that to mean it's not a bug but doesn't seem to work like I expect it to.

**Comment by uzaxirr** [comment]
If i'm not wrong then this issue should be closed via #280 
If no then please enlighten me on the additional work that should be done

**Comment by kaihoffman** [comment]
Closed via #280 thank you for the nudge @uzaxirr
