### ISSUE TITLE
civo regions db not available to cli

### ISSUE THREAD

**Issue by ripro-patrick** [civo/cli#329]
when running 
```
civo region ls
```

I receive the following error:
```
Please check if you are using the latest version of CLI and retry the command 
If you are still facing issues, please report it on our community slack or open a GitHub issue (https://github.com/civo/cli/issues) 
Error: Error: Unknown error response - status: 404 Not Found, code: 404, reason: {"code":"database_region_not_found","reason":"Failed to find the region within the internal database"}

```

Verified with civo cli version:
- v1.0.59
- v1.0.48

**Comment by alejandrojnm** [comment]
Hi @ripro-patrick we are aware of this, but the problem is this 
https://status.civo.com/issues/2023-07-10-nyc1-region-disruption/

**Comment by ripro-patrick** [comment]
Hi @alejandrojnm 
Thanks for the very swift update.
Oh, I see you have much bigger troubles than just my little thingy.
I hope you can get it solved soon :-)

**Comment by alejandrojnm** [comment]
For now what you can do is use another region like LON, FRA1. or PHX1, you can edit `~/.civo.json` and change the default region to one of that. Like this `"default_region":"LON1"`. Hope this help and help you to sort the problem
