### ISSUE TITLE
civo update fails with NoAPIKeySuppliedError if I don't have an API key 

### ISSUE THREAD

**Issue by rberrelleza** [civo/cli#334]
```
$ civo update
Creating the connection to Civo's API failed with NoAPIKeySuppliedError: no API Key supplied, this is requiredNoAPIKeySuppliedError: no API Key supplied, this is required
```

deleting $HOME/.civo.json fixed the issue for me

**Comment by alejandrojnm** [comment]
mm, that is odd, the update doesn't use the ApiKey to update the binary, @haardikdharma10 can you check this

**Comment by fharper** [comment]
I had the same issue when I deleted the `tempKey` as I was testing something with the API keys. The CLI should at least let you save a new API key, when there's none, and also check the help menu so you know how to do it. I'm on v1.0.61.

**Comment by alejandrojnm** [comment]
I will check this

**Comment by alejandrojnm** [comment]
@rberrelleza @fharper I just checked this and the cmd update doesn't use the API to update the binary. I will close this issue for now, If need to reopen please feel free to do it.
