### ISSUE TITLE
Saving API key doesn't seem to work

### ISSUE THREAD

**Issue by fharper** [civo/cli#335]
I tried to save a new API key, and it's kinda intermittent, not working most of the time, but not giving me an error. Unless I'm mistaken on the process, you can see in the screenshot that I added a new key under the name `test2`, but it's still not available.

I've been able to reproduce this with about 10 tests, but once it worked after I reloaded my shell (meaning the `ls` shown the new key I added that wasn't there before I reload), but only once.

<img width="753" alt="CleanShot 2023-08-29 at 16 05 54@2x" src="https://github.com/civo/cli/assets/1170989/9e0ccbdb-11bb-4eb7-b58d-e86572d5e60d">

**Comment by fharper** [comment]
Just found the issue. They new key was saved, but won't display if I have an environment variable `CIVO_TOKEN` set. When I unset it, the new key was available.

Also, if I unset `CIVO_TOKEN`, and select the new key, the second `CIVO_TOKEN` is set again, the selected API key fallback to `tempKey`.

Not sure how the CLI is using this environment variable, and maybe it's the wanted behavior (as in if you have this variable set, it's probably the key you want to use) but I would expect still being able to set different api keys if I want to manage multiple accounts with the CLI, and yeah, maybe use `CIVO_TOKEN` as the default key when the user didn't select or add any new ones.

**Comment by alejandrojnm** [comment]
I'm checking this, but we added that adoption to allow people to use the CLI in any CI/CD so you add the env variable and you don't need to worry about adding the new API key and select, automatically that key will be the default one.

**Comment by alejandrojnm** [comment]
Maybe we need to add this to the readme
