### ISSUE TITLE
Change default behavior of k8s config save.

### ISSUE THREAD

**Issue by Johannestegner** [civo/cli#37]
In the current implementation, you are required to use the `--merge` (`-m`) flag if you wish that the `civo kubernetes config --save` command merges the configuration.  
For people who have used the CLI for a while, this is not a huge issue as we know about it, but I have noticed that people that are new to using it (just as with me when I first tried it out), this is missed.

I propose that one of the following changes are made to the behavior:

Alt 1. `--merge` is used by default, and a `--replace` flag is added for people who really don't want to keep their configuration.

Alt 2. A confirmation mentioning that the old configuration will be deleted.

Neither of the above would be such a breaking change that people would have issues with using the cli and it would be a lot "safer" for new users.

**Comment by alejandrojnm** [comment]
Hi @Johannestegner when you use the `--save` option there is a warning like this:
```
alejandrojnm@Mac-mini-de-Alejandro cli % ./civo kubernetes config intance-operator --save
Warning: Are you sure you want to overwrite the kubernetes config (y/N) ? 
```
and if you run non-interactively you can use with the `-y` that will assume "yes" as answer to all prompts
