### ISSUE TITLE
Allow Civo Volume rm to accept multiple volumes 

### ISSUE THREAD

**Issue by DMajrekar** [civo/cli#375]
Currently when deleting volumes with the following command 

```
civo volume rm -y e81bcb4d-0e51-414d-b65b-7391b8c4553b 538484f9-5fbe-4a9e-9521-d0a73c1d7d47 5bf6a755-2f50-47a5-9592-d0addb6a1096 8e17ee56-d905-48a6-84e9-eef963cb7ee0 d076893f-da1c-4017-acc9-1bc142ffffcc ecb5786e-3d83-453f-84d7-a61e364fd762 6ce18e88-755e-478c-aeb5-507116bbfc99 8af2c895-4c57-4762-8fa1-b3886c7b9ca5
```

only the first volumes is deleted
```
The volume called pvc-5dce1ae7-e388-4805-b2d6-11ac8d2e9d62 with ID e81bcb4d-0e51-414d-b65b-7391b8c4553b was deleted
```

**Comment by fernando-villalba** [comment]
I second this. It would also make it more consistent with the behaviour of the `kubernetes` and `objectstorage` commands

**Comment by haardikdharma10** [comment]
@fernando-villalba this should be fixed with - https://github.com/civo/cli/pull/430

**Comment by haardikdharma10** [comment]
Fixed in latest release - https://github.com/civo/cli/releases/tag/v1.0.87
Closing.
