### ISSUE TITLE
Firewall Rule Create Value Checking

### ISSUE THREAD

**Issue by jhanley-com** [civo/cli#382]
Problem description:

The CLI accepts invalid addresses for the --cidr flag.

Example: --cidr=%CIDR

Complete Command:

civo firewall rule create %NAME% ^
--protocol=TCP ^
--startport=1 ^
--endport=65535 ^
--direction=ingress ^
--label="Allow all TCP traffic from home" ^
--action="allow" ^
--cidr=%CIDR

The error is caused by a typo "%CIDR" should be "%CIDR%. In the script file I use environment variable substitution because I create multiple rules in one batch file.

I realize that validating IP addresses can be a pain, but the characters "%CIDR" are not valid for IPv4 addresses. Perhaps the "C" if you accept hex addressing, but I did not test that.

Problem level: nuisance - not critical

Environment:
CLI version: 1.0.80
OS: Windows 10 x64
Command Prompt (not PowerShell)

**Comment by alejandrojnm** [comment]
Thanks @jhanley-com for this report, @uzaxirr can you check this, also I think it is possible to validate the CIDR before send to CIvo
