### ISSUE TITLE
Allow switching instance back to using default firewall

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#39]
This came through as a customer query.

The web panel allows users to switch instances back to use the default firewall. The CLI does not allow for a switch back to Default, only from Default to a new firewall, or between two named user-created firewalls.

When I do `civo firewall list` the default firewall (or anything referring to it is not shown on the CLI).

**Comment by alejandrojnm** [comment]
@kaihoffman the problem with that is the `default` rule don't come in the API request

**Comment by kaihoffman** [comment]
The frontend UI uses the same API to communicate with the instance backend. I can try and see what the request looks like when you swap on the web UI

**Comment by alejandrojnm** [comment]
if you run this:
```
curl -H "Authorization: bearer token_here" https://api.civo.com/v2/firewalls
```
you will saw the `default` firewall is not in the list

**Comment by kaihoffman** [comment]
Yep, I can see that - the output of GET v2/firewalls is the listing of all available firewalls. But somehow the web-UI knows how to do it 🤔 I'll have a dig.

**Comment by zulh-civo** [comment]
@kaihoffman any update from your end? Does the GET v2/firewalls include `default`?

**Comment by zulh-civo** [comment]
I'm seeing this issue from two sides:

1. A user launched an instance on _network A_ with _firewall A_ and wants to change it to _firewall B_ (or default firewall) within the same _network A_
2. A user launched an instance on _network A_ with _firewall A_ and wants to change it to _firewall X_ in another network (say, _network X_)

Can we scope this issue to only cover case number 1? @andyjeffries 

For case number 2, it's tracked internally at Civo (for Civo staff: as issue 10 in civo/api). Once we are done with it, then we add it here. I can create a separate issue for that.

**Comment by andyjeffries** [comment]
100% scope to only 1.

We don't support moving of instances between networks - I believe it's not supported at the Kubernetes level so without major workarounds, we're unlikely to do so.
