### ISSUE TITLE
Reconsider behaviour when providing a value lower than 500 for bucket size

### ISSUE THREAD

**Issue by fernando-villalba** [civo/cli#394]
## Issue

The current behaviour when passing a value lower than 500 for bucket size is to ask this question:

```bash
Warning: The minimum size to create an object store is 500 GB. Would you like to create an object store of 500 GB? (y/n) ?
```

There are some issues with this approach

1. It doesn't respect the `--yes` flag:

```bash
% civo bucket create --yes --size 50 test-ticket 
Warning: The minimum size to create an object store is 500 GB. Would you like to create an object store of 500 GB? (y/n) ?
```
2. It should perhaps fail without asking anything.

If this command was part of a script, it would halt execution, if it fails, it's better. 

3. The help of the command needs to make it explicit that the minimum is 500, default is not the same as minimum, it should perhaps say `default/minimum`

```bash
-s, --size int                  Size of the Object store (default 500)
```

## Acceptance criteria

There are two ways to tackle this

* Fail lower values with a message that the minimum is 500, also change the help to explicitly say that the minimum is 500 --> preferred
* Respect the `--yes` flag, and also change the help to explicitly say the minimum is 500
* Automatically ignore lower values and assign 500 GBs, provide a warning when doing so --> This may give users the illusion they are paying less than they will if they are not paying attention, so perhaps not the best course of action.

**Comment by harsh082ip** [comment]
Is there anyone working on this issue?
@fernando-villalba @uzaxirr

**Comment by harsh082ip** [comment]
If not, can you please assign it to me, I want to work on this

**Comment by harsh082ip** [comment]
I have made a PR regarding this issue.
Please review and let me know if any changes are needed.
@fernando-villalba @uzaxirr @RealHarshThakur @haardikdharma10
