### ISSUE TITLE
Restore --wait --save --switch functionality

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#4]
On the previous Ruby CLI, you could run `civo kubernetes create test --wait --save --switch` which would display the time the cluster took to launch, save the config (or merge if another config existed) and then switch to that context on completing.

I find it very handy to use when I create a test/demo cluster and want to immediately use it when it's ready.

**Comment by alejandrojnm** [comment]
@andyjeffries currently this option is not at the moment of creating the cluster, but is in `civo k3s config --save --merge`, what could be adding` --switch` in this option, or do you think it would be valid to put  `--save` `--merge` and `--switch` at the moment of the cluster creation

**Comment by andyjeffries** [comment]
I think it's valid to accept all of them. I think having `--save` actually do a merge is useful/a good idea too. So maybe that's just an alias?

**Comment by alejandrojnm** [comment]
closed with the release [v0.6.15](https://github.com/civo/cli/releases/tag/v0.6.15)
