### ISSUE TITLE
Unable to install app via CLI

### ISSUE THREAD

**Issue by zulh-civo** [civo/cli#42]
@alejandrojnm, when I try to install WordPress app from Civo CLI (`civo k8s apps add Wordpress:5GB [--cluster my-cluster]`), I got this error:

```
The application was installed in the Kubernetes cluster
```

I retry it in new clusters as well but the error persist. But when I switched to Civo web UI, I'm able to install it just fine.

I'm not quite sure if the problem was originated from a piece of code in this repository OR it's from Civo back-end. Something for us to investigate and fix.

**Comment by alejandrojnm** [comment]
i will check this, Ta @zulh-civo

**Comment by alejandrojnm** [comment]
This is fix now
