### ISSUE TITLE
Creating networks with the CLI does not create a default firewall rule for it

### ISSUE THREAD

**Issue by fernando-villalba** [civo/cli#428]
## Issue

The default network has a default firewall that cannot be deleted.

When creating another network in the UI, it also creates a default firewall that also cannot be deleted. 

Creating a network in the CLI however does not create this default firewall.

This issue also affects the [Terraform provider](https://github.com/civo/terraform-provider-civo/issues/212).

## Acceptance criteria

* Ensure the behaviour of the CLI matches that of the UI. When a network is created, a default firewall should also be created.

**Comment by haardikdharma10** [comment]
Closing as completed in https://github.com/civo/cli/pull/431
