### ISSUE TITLE
Default to case insensitive in instance/cluster/apikey/etc names

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#43]
This is from feedback by a user completing KubeQuest, and I think it's a good one.

Would it be possible to have CLI commands not care about case in input? So that if you had a cluster called My-Kubernetes-Cluster, it would be found with `civo k8s show my-kubernetes-cluster` as well as specific capitalization.

I don't know how hard it is to implement in Golang, but having it at least as an option would be great IMO

**Comment by BjoernAkAManf** [comment]
Also see https://github.com/civo/civogo/pull/49 for a PR in the underlying library.
