### ISSUE TITLE
Feature request: region selection

### ISSUE THREAD

**Issue by mciverza** [civo/cli#44]
Feature request:
Region listing is possible, we should be able to select/set the defaul region too :-)

```
civo region ls
```
for example
```
civo region set NYC1
```

Does a generic region selection needed to be added to all the `create`  commands too?

e.g 
```
civo kubernetes create mycluster --region=NYC1 --size=g2.large --nodes=3 
```

**Comment by alejandrojnm** [comment]
Hi we are ready working on this 👍

**Comment by alejandrojnm** [comment]
This is ready in the version [v0.7.0](https://github.com/civo/cli/releases/tag/v0.7.0)
