### ISSUE TITLE
Listing firewalls with no rules doesn't display relevant information

### ISSUE THREAD

**Issue by fernando-villalba** [civo/cli#447]
## Issue

Listing firewalls with no rules doesn't display helpful or relevant information

1. Create a firewall without rules
```
civo fw create test-issue --create-rules=false 
```

2. List the firewall without rules

```
civo firewall rule ls test-issue 
```

Output:

<img width="815" alt="image" src="https://github.com/user-attachments/assets/0c8d17d2-120f-4f96-9598-b5800771d401">

## Acceptance Criteria

The output provided above is not helpful. Instead, the message should be something like:

```
Firewall test-issue has no rules, to create rules use command civo firewall rule create, for example:
civo firewall rule create test-issue -c '0.0.0.0/0' -s 443 -e 443 -l HTTPS
```

Or something like that

**Comment by Praveen005** [comment]
Hi Team,

for this issue, adding a check to see if `firewallRules` slice is empty and erroring out with the above suggested message would be okay I believe.

<img width="765" alt="Screenshot 2024-08-12 205407" src="https://github.com/user-attachments/assets/6339257c-d3fa-4104-8464-cc11373d3444">


Result:

<img width="667" alt="Screenshot 2024-08-12 205108" src="https://github.com/user-attachments/assets/8d1f487f-b755-4467-91e9-f6af93899485">
