### ISSUE TITLE
Show database PrivateIP

### ISSUE THREAD

**Issue by vishalanarase** [civo/cli#455]
* Show the database PricateIP field in the CLI 
* Civogo is returning in the response

**Comment by Praveen005** [comment]
Hi @uzaxirr 

#456 fixes this.

I had a question, should we also show the PrivateIP on `civo database ls db_name` command? like this:

<img width="672" alt="Screenshot 2024-09-04 154753" src="https://github.com/user-attachments/assets/9a6c2a30-f425-4a8a-ba59-3a5930197db5">


Currently output looks like:

<img width="584" alt="Screenshot 2024-09-04 154848" src="https://github.com/user-attachments/assets/76d43d10-43b8-48a0-8886-f06ec56c66db">

**Comment by uzaxirr** [comment]
hii @Praveen005 yes it would be nice to add it in this cmd as well
