### ISSUE TITLE
Region flag isn't respected when creating instances

### ISSUE THREAD

**Issue by dwoolger** [civo/cli#460]
**Description**

When creating instances, the region flag is not respected.

**Reproducing**

1. Switch to a region where the diskimage isn't available (in this case phx1)

$ civo region current phx1
The default region was set to (phx1) phx1

2. Confirm disk image isn't available...
$ civo diskimage ls | grep debian-9
...no results returned...

3. Attempt instance creation...

$ civo instance create -t debian-9 -s host --region lon1
Please check if you are using the latest version of CLI and retry the command
If you are still facing issues, please report it on our community slack or open a GitHub issue
Error: The provided disk image is not valid

4. Switch region to lon1 & confirm disk image...

$ civo region current lon1
The default region was set to (lon1) lon1
$ civo diskimage ls | grep debian-9
| 9b661c46-ac4f-46e1-9f3d-aaacde9b4fec | debian-9        |              9 | available | debian       |
 
5. Instance creation is then successful...

$ civo instance create -t debian-9 -s host --region lon1
The instance host has been created

$ civo instance rm -y host

6. Switching to a region where the diskimage is valid...

$ civo region current fra1
You are already using that region: fra1
$ civo diskimage ls | grep debian-9
| 2d0985a8-c011-4c82-b163-e95b26df0a82 | debian-9     |       9 | available | debian       |

7. Creating an instance targeted at lon1, but gets created in fra1...

$ civo instance create -t debian-9 -s host --region lon1
The instance host has been created

$ civo instance ls
+--------------------------------------+----------+--------+-----------+-----------+------+----------+---------------+--------------+--------+
| ID                                   | Hostname | Region | Size      | Cpu Cores | Ram  | SSD disk | Public IP     | Private IP   | Status |
+--------------------------------------+----------+--------+-----------+-----------+------+----------+---------------+--------------+--------+
| e3b8fb3d-bb68-4c61-a8d0-b08c7fcc4f62 | host     | fra1   | g3.medium |         2 | 4096 |       50 | x.x.x.x | x.x.x.x | ACTIVE |

**Comment by uzaxirr** [comment]
Hey, this has probably been fixed by: https://github.com/civo/cli/pull/453

can you update your CLI to latest version and check again.
