### ISSUE TITLE
Installing app scales cluster to zero

### ISSUE THREAD

**Issue by andyjeffries** [civo/cli#47]
@mciverza wrote in https://github.com/civo/kube100/issues/62

after launching a cluster, manually adding an application via CLi scales the cluster to zero
It might also be true via WebUI, but I have not yet tested it

![2021-02-11_08-00-civo-app-scales-cluster](https://user-images.githubusercontent.com/20853599/107606947-64d01f80-6c40-11eb-86f7-169eeda5ab47.png)

obtained by creating cluster via CLi, 

```
civo k3s create tinytest3 -s g2.small --nodes 2 -r traefik
```

waiting until cluster is green

```
civo k3s list
```

and then adding Nginx

```
civo k3s applications add Nginx -c tinytest3
```

shown by again running

```
civo k3s list
```

**Comment by mciverza** [comment]
looks good now.
adding app did not affect node count.
