### ISSUE TITLE
volumetype functionality

### ISSUE THREAD

**Issue by alessandroargentieri** [civo/cli#473]
Some regions are flagged with the `custom_storage_class: true`:
```bash
$ curl -H "Authorization: Bearer `mycivoapikey`" https://api.civo.com/v2/regions | jq
[
  {
    "code": "<regionCode>",
    "name": "<regionName>",
    ...
    "features": {
         ... 
         "custom_storage_class": true
    },
  },
``` 
For these regions we would like to add the new command:
```bash
civo volumetypes ls
```
This will wrap a HTTP call returning a JSON array of elements like:
```
GET /v2/volumetypes
Response:
[
   {
     "name": "ms-xfs-2-replicas"
     "description": "<OPTIONAL>",
     "flags": ["foo", "bar"] // OPTIONAL
   },
   {
      "name": "ms-xfs-3-replicas"
      "description": "<OPTIONAL>",
      "flags": ["foo", "bar"] // OPTIONAL
    },
]
```
The user can select a volumetype.name and pass to the following:
```
civo instance create myinstance --volume-type=<VOLUMETYPENAME_HERE>
civo volume create myvolume --volume-type=<VOLUMETYPENAME_HERE>
```
The  `civo instance show <INSTANCE_NAME>` and the `civo volume show <VOLUME_NAME>` will show the VolumeType if it comes in the response (optional).

N.B. It needs a new civogo tag @fulviodenza can you provide it?

**Comment by fulviodenza** [comment]
@alessandroargentieri  Sure, I will do as soon as the PR https://github.com/civo/civogo/pull/209 is merged

**Comment by fulviodenza** [comment]
Here is the tag [0.3.82](https://github.com/civo/civogo/releases/tag/0.3.82)
