### ISSUE TITLE
Aliases for `kubernetes` command

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#5]
There are a number of aliases in the CLI already, but it would be great if `kubernetes` would be invoked with aliases e.g. k3s, k8s:

`$ civo k8s show my-cluster`
`$ civo k3s ls`

**Comment by alejandrojnm** [comment]
@kaihoffman that alias exist in the current version:

```
civo kubernetes -h       
Details of Civo Kubernetes clusters

Usage:
  civo kubernetes [command]

Aliases:
  kubernetes, k3s, k8s, kube
```
