### ISSUE TITLE
Show available sizes

### ISSUE THREAD

**Issue by mciverza** [civo/cli#51]
The CLi helpfully requires correct node size to be specified, where can the list of valid sizes be obtained?

e.g
```
civo@krew:~$ civo k3s create kickit5 --size k3s.small --nodes 2
Error: DatabaseServiceNotFoundError: Failed to find the size within the internal database
```

**Comment by alejandrojnm** [comment]
you can run `civo size ls` and you will see all size for the region, i will try to suggest the size at the moment of the creation
