### ISSUE TITLE
overwriting kubeconfig by default

### ISSUE THREAD

**Issue by mciverza** [civo/cli#52]
Civo CLi seems to want to override kubeconfig by default now.
it should not update Kubeconfig, unless `--switch` and/or `--merge` are specified:

e.g 
```
civo@krew:~$ civo k3s create kickit5  --nodes 2
Warning: Are you sure you want to overwrite the kubernetes config (y/N) ? y
```

**Comment by alejandrojnm** [comment]
ok i will check this

**Comment by alejandrojnm** [comment]
Close by https://github.com/civo/cli/commit/8346ff2023d19f494c1f945337f9f0d5926432e8
