### ISSUE TITLE
Missing Region Information (Bug|Question)

### ISSUE THREAD

**Issue by martynbristow** [civo/cli#56]
When using the civo CLI, it will default to region (nyc1) which means for legacy instances and clusters, you get no data, without informing the user.

Question:
What should the correct behavior be?

* Should it default to NYC1? - As a user I'd expect an `ls` to return all resources across all regions
* How should the user supply the region. Its not mentioned in the README, I'd happily submit a PR but I'm not sure how it would convey it best

**Comment by martynbristow** [comment]
Also region must be SVG1 and not svg1
Using an invalid region causes a silent fail

**Comment by alejandrojnm** [comment]
HI @martynbristow if you choose NYC in the UI the that will your default region if you don't have one in the config file, if you have one in the config file the CLI will be use that.

**Comment by martynbristow** [comment]
It looks like NYC1 is the default region unless you have explicitly set `default_region: SVG1`, --region=SVG1, `?region=SVG1`
The UI selection doesn't seem to be taken as mine is set to SVG1

All my tokens have `lon1` set for legacy reasons

When default region is REMOVED from the civo.json:

```
martyn@MacBook-Pro civo-cli % civo instance ls
Warning: No region set - using the default one - set a default using "civo region current REGION" or specify one with every command using "--region=REGION"
Error: UnknownError
```

When it "was" set to 'lon1' prior to the upgrade:
```
martyn@MacBook-Pro civo-cli % civo instance ls
Error: UnknownError
```

It's effectively a breaking change for legacy users, who would have 'lon1' set, also its not verifying the parameter it opens to bugs.
---
As a minimum could we have something at the top of the README to inform users about this behavior.

Personally I'd reject any command where region is not valid, or region is not empty.
I.e. default_region=lon1, default_region=svg1 -> Error

**Comment by DoNnMyTh** [comment]
@martynbristow I'll update the readme tomorrow stating that default location is NYC1 and instructions for SVG1

**Comment by alejandrojnm** [comment]
@martynbristow what you put in the CLI is not reflected in the UI, if by default you don't have any SVG1 will be used, i will think in a nice solution for the legacy config.

**Comment by alejandrojnm** [comment]
@martynbristow i add this message now:

`Warning: No region set or you are using a deprecate one - using the default one - set a default using "civo region current REGION" or specify one with every command using "--region=REGION"`

Now if you config file have `lon1` i will show that message

**Comment by DoNnMyTh** [comment]
@alejandrojnm @martynbristow i think adding a deprecated function for LON1 can create a issue later as SVG1 will be going away and LON1 will take its place, so this can create more confusion. i think [API documentation page](https://www.civo.com/api) needs to be updated and it will be much better

**Comment by andyjeffries** [comment]
I think we need some code in the CLI to change lon1 (if it's lowercase) -> SVG1 (originally OpenStack was lon1, but we've renamed it to SVG1 as we'll launch a CivoStack LON1).

**Comment by martynbristow** [comment]
Thanks Andy ... works for me.
This is the issue I had
Although I'm not sure how handing a future unknown region should be, as that's effectively what's happening.

**Comment by DoNnMyTh** [comment]
@martynbristow So may be close it now and [Api Documentation](https://www.civo.com/api) will be updated soon 😊
