### ISSUE TITLE
It would be nice to able to view a applications post install instructions from the CLI

### ISSUE THREAD

**Issue by gezb** [civo/cli#60]
It would be nice to be able to view an applications post_install.md instructions from the cli after adding an application to your cluster

I would see it being another option  on the applications command e.g. `civo k8s applications post-install-docs <app-name>`

I found this library that could maybe be used https://github.com/MichaelMure/go-term-markdown?

I am happy to look at creating a PR for this if you think this would be a good idea?

**Comment by alejandrojnm** [comment]
Hi, thanks for this, but i think it will more helpful if we use in the `kubernetes` cmd like this:

```bash
civo k3s show CLUSTER_NAME --app MinIO
```
i saw you PR, but i don't like the idea to hard code a Url, that is why i decide to move the option to `kubernetes` cmd 
i have the implementation ready, i will push tonight, and create new release

**Comment by gezb** [comment]
OK Thanks, no problem.  

The reason I hard coded the URL is I wasn't aware of any other way of locating the post_install.md file (edit I should have looked closer at the go client - I see there is a postinstall field the returned struts :) ) 

Does your implementation mean the app has to be installed in CLUSTER_NAME before you  can view the post install file? I was trying to mirror the functionally on the webpage where you can view the post install steps before installing an application
