### ISSUE TITLE
Native Apple Silicon Compatibility (arm64-darwin)

### ISSUE THREAD

**Issue by beret** [civo/cli#61]
On Apple Silicon/ARM64, the https://civo.com/get script properly identifies the platform, but the target package has not been built. (https://github.com/civo/cli/releases/download/v0.7.5/civo-0.7.5-darwin-arm.tar.gz) I have not tested with homebrew, though I suspect it properly falls back to the amd64 packages.

To install on Apple Silicon, amd64 builds can of course be manually downloaded and run through Rosetta. This revision to the script invocation also overrides arch detection: `curl -sL https://civo.com/get | arch -x86_64 sh`

Go release 1.16 (February 2021) adds support of 64-bit ARM architecture on macOS (Apple Silicon) via the GOOS=darwin and GOARCH=arm64  
https://tip.golang.org/doc/go1.16#darwin

("Universal binaries" are [not yet supported](https://github.com/goreleaser/goreleaser/issues/2070) by the Go build process.)

**Comment by alejandrojnm** [comment]
Hi @beret can you check the last version of the [CLI v0.7.6](https://github.com/civo/cli/releases/tag/v0.7.6), i made some change in the CI to build the binary for `darwin/arm64`, just test and let me know

**Comment by beret** [comment]
The script still expects an -arm suffix on the URL, rather than the -arm64 in the release, but when that is corrected the script properly pulls the code and installs, and I get a Mach-O arm64 binary that runs fine. Thanks for the quick addition of the build!

file $(which civo)                                                                                                                                                                                                        
/usr/local/bin/civo: Mach-O 64-bit executable arm64
uname -a                                                                                                                                                                                                              
Darwin hostname.local 20.4.0 Darwin Kernel Version 20.4.0: Wed Feb 10 23:06:18 PST 2021; root:xnu-7195.100.326.0.1~76/RELEASE_ARM64_T8101 arm64
uname -m                                                                                                                                                                                                                  
arm64
