### ISSUE TITLE
UnknownError when listing instances and no instances exist

### ISSUE THREAD

**Issue by maelvls** [civo/cli#63]
When running `instance ls`, I get an `UnknownError`:

```sh
% civo --region NYC1 instance ls
Error: UnknownError
```

I used mitmproxy to understand what was going on. The HTTP request that `civo` makes is:

```http
GET /v2/instances?page=1&per_page=99999999&region=NYC1 HTTP/1.1
Host: api.civo.com
User-Agent: civogo/0.2.21
Accept: application/json
Authorization: bearer redacted
Content-Type: application/json
Accept-Encoding: gzip
```

and the response is:

```http
HTTP/1.1 200 OK
Date: Wed, 03 Mar 2021 17:09:19 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
X-RateLimit-Limit: 50
X-RateLimit-Remaining: 48
ETag: W/"c36c6615f45d86a1351e8eb57f6c8df2"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: ee85b170e9f92c2c3c4fd52c87410d8d
X-Runtime: 1.324644
Vary: Origin
X-RateLimit-Reset: 1614791400
Strict-Transport-Security: max-age=15724800; includeSubDomains

{"page":"1","per_page":null,"pages":0,"items":[]}
```

Does it fail because I do not have any instances?

**Comment by martynbristow** [comment]
The issue is actually in the civogo library, not the cli wrapper.

The error is an `UnmarshallTypeError`

The answer looks to be in: `{"page":"1","per_page":null,"pages":0,"items":[]}` which should be: `{"page":1,"per_page":null,"pages":0,"items":[]}`.

I've checked when you have an instance in SVG1 you get: `1` but when no instances in NYC1 you get `"1"`

The error is because:
```
type PaginatedInstanceList struct {
	Page    int        `json:"page"`
	PerPage int        `json:"per_page"`
	Pages   int        `json:"pages"`
	Items   []Instance `json:"items"`
}
```
Expects an int and it should be a string

@andyjeffries Any thoughts

**Comment by alejandrojnm** [comment]
This is already fix

**Comment by maelvls** [comment]
@martynbristow Thank you for the thorough details!

> This is already fix

When do you think I may expect the fix to be merged and released? I use the `civo` CLI through Homebrew.

**Comment by martynbristow** [comment]
Are you still seeing the issue?

```
martyn@MacBook-Pro ~ % civo instances ls --region=NYC1
martyn@MacBook-Pro ~ %
```

I can't reproduce it anymore, as it was an upstream issue it may well have been patched there for you

**Comment by alejandrojnm** [comment]
Hi guys is already fix from the API side, so there is not need to update the CLI or the Civogo lib
