### ISSUE TITLE
Using the remove application flag for traefik does not work via the CLI

### ISSUE THREAD

**Issue by keithhubner** [civo/cli#64]
Using the -r flag to remove traefik only works via the GUI, this doesn't seem to work via the CLI.

`civo k3s create -r traefik --save --wait`

`kubectl get pods -A`

`kube-system   traefik-6f9cbd9bd4-2cg48                  1/1     Running     0          86s`

**Comment by alejandrojnm** [comment]
i will check this, Ta @keithhubner

**Comment by alejandrojnm** [comment]
Hi @keithhubner sorry for the delay, i test the same and it work, the only difference is i put the name of the app in this way 
`civo kubernetes create -r Traefik --wait ` and the `get pods -A` return this:

```bash
KUBECONFIG=civo-autumn-cliff-kubeconfig kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   metrics-server-86cbb8457f-sh7fc           1/1     Running   0          91s
kube-system   local-path-provisioner-7c458769fb-jdr7h   1/1     Running   0          91s
kube-system   coredns-854c77959c-rkjr4                  1/1     Running   0          91s
```
