### ISSUE TITLE
Feature request: auto complete

### ISSUE THREAD

**Issue by amitech** [civo/cli#68]
Being a Linux user I miss auto completion of options with tab.

It will be great if Civo CLI can auto complete like most of the Linux commands does. It will help in lesser human errors while performing different operations using CLI.

**Comment by alejandrojnm** [comment]
i am working on that, the kubernetes cmd has that, my plan is to complete it before the month is up

**Comment by owlreddy** [comment]
`source <(civo completion bash)` ran this command and auto completion seems to be working. It's a bit slow but it's working

**Comment by amitech** [comment]
Thanks @csor-dev for pointing it out.
