### ISSUE TITLE
civo-0.7.8-darwin-arm64.tar.gz : dyld: Symbol not found: _clock_gettime 

### ISSUE THREAD

**Issue by hasorli** [civo/cli#70]
Can not upgrade from 

 ./civo version
Civo CLI v0.7.5  

to 0.7.8-darwin

get error: 

 ./civo 
dyld: Symbol not found: _clock_gettime
  Referenced from: /xxx/xxx/tmp/civo-test/078/./civo
  Expected in: flat namespace

Trace/BPT trap: 5

Civo CLI v0.7.5   is the latest version its possible to run. (Also tested 0.7.7 and 0.7.6 with the same result)

**Comment by alejandrojnm** [comment]
what step you fallow to do that ??

**Comment by hasorli** [comment]
$ mkdir "newtestdir"
$ cd "newtestdir"
$ wget https://github.com/civo/cli/releases/download/v0.7.8/civo-0.7.8-darwin-amd64.tar.gz
$  tar zxvf civo-0.7.8-darwin-amd64.tar.gz 
$ ./civo 
dyld: Symbol not found: _clock_gettime
  Referenced from: /xxxx/xxxx/tmp/civo-test/1/./civo
  Expected in: flat namespace

Trace/BPT trap: 5

**Comment by alejandrojnm** [comment]
what version of Mac OS you have  ??, can you try this `xcode-select --install`

**Comment by hasorli** [comment]
Systemversjon:	OS X 10.11.6 (15G22010)
Kernel-versjon:	Darwin 15.6.0

$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

$ xcode-select --version
xcode-select version 2343.


I successfully compiled the source on the same machine (make ) with : 
go version
go version go1.15.8 darwin/amd64

and was able to run 
./civo version
Civo CLI v0.7.8

**Comment by alejandrojnm** [comment]
Can you run **civo version -v**
Also you Mac is the new Mac with M1 micro???

**Comment by alejandrojnm** [comment]
i will close this, if you have another problem, always you can open again.

**Comment by hasorli** [comment]
./civo version -v
Client version: v0.7.8
Go version (client): go1.15.8
Build date (client): 2021-03-10T19:07:59CET
Git commit (client): b686acccc4d05dc8732e37fc809979e9a010ab4d
OS/Arch (client): darwin/amd64

> Mac is the new Mac with M1 micro???  

No. It`s an older MacBook Air, 1,8 GHz Intel Core i7
