### ISSUE TITLE
civo kubernetes rename Nyc-Pizza Nyc-Pizza1 Triggers rescaling

### ISSUE THREAD

**Issue by DoNnMyTh** [civo/cli#71]
When i use civo kubernetes rename Nyc-Pizza Nyc-Pizza1 it should rename the cluster or give error on invalid format instead it triggers a re scaling.

![image](https://user-images.githubusercontent.com/17374859/110805862-80fac700-82a7-11eb-9212-29b2f00e93ff.png)

**Comment by DoNnMyTh** [comment]
Which i clearly used command ```  civo kubernetes rename Nyc-Pizza Nyc-Pizza1 ```
![image](https://user-images.githubusercontent.com/17374859/110806297-efd82000-82a7-11eb-9b32-2ceee835fa68.png)

**Comment by alejandrojnm** [comment]
We are working on this now

**Comment by DoNnMyTh** [comment]
Awesome Ale :)
