### ISSUE TITLE
Undescriptive "Error: UnknownError" on network errors

### ISSUE THREAD

**Issue by maelvls** [civo/cli#73]
Hi,

I am using `civo` 0.7.9. If I turn off my internet, I get a non-descriptive error:

```sh
% civo --region NYC1 kubernetes ls
Error: UnknownError
```

Is that intended? I wish the error would rather talk about a network issue, e.g.,

```sh
Error: unable to connect to the server: dial tcp 212.2.242.122:6443: connect: network is unreachable
```

**Comment by alejandrojnm** [comment]
Ok, i will check this, Thanks for this
