### ISSUE TITLE
civo kubernetes config shouldn't overwrite the kubeconfig.

### ISSUE THREAD

**Issue by JasonMorgan** [civo/cli#75]
It should default to adding an entry for the cluster similar to what k3d does. It's pretty common for cluster creation tools.

**Comment by alejandrojnm** [comment]
what cmd you run, in any case the CLI ask if you wanna overwrite, but if you use `--merge` add a new entry to your kubeconfig

**Comment by JasonMorgan** [comment]
Definitely! I was trying to suggest merging should be the default behavior.

**Comment by zulh-civo** [comment]
Should we make merge as default behaviour, @andyjeffries @alejandrojnm?

**Comment by andyjeffries** [comment]
Yeah, I'd agree with that. A better developer experience. And make `--overwrite` be a switch that intentionally overwrites the existing file.
