### ISSUE TITLE
Using -r or --remove-applications Throws error in 0.7.9

### ISSUE THREAD

**Issue by DoNnMyTh** [civo/cli#76]
In Release 0.7.9 using flag -r or --remove-application throws an error. 

![image](https://user-images.githubusercontent.com/17374859/113282061-0c460600-9304-11eb-8977-dd0f51c9514b.png)

Version 0.7.8 works fine. 
![image](https://user-images.githubusercontent.com/17374859/113282084-1536d780-9304-11eb-9e4c-3fb7cfb067d6.png)

**Comment by alejandrojnm** [comment]
I'm working on this
