### ISSUE TITLE
I'm facing an error while creating cluster via CLI

### ISSUE THREAD

**Issue by owlreddy** [civo/cli#77]
when I run `civo kubernetes create` I get an error saying 
`Error: Error checking availability ZeroMatchesError: unable to find SGV1, zero matches`

**Comment by alejandrojnm** [comment]
Yep, that is the legacy configuration, you need set a zone, `civo region current SVG1 or NYC1`

**Comment by owlreddy** [comment]
SVG1 seems to be restricted but NYC1 worked. Thank you

**Comment by andyjeffries** [comment]
Just to add to this for anyone finding this in the future - SVG1 is our old OpenStack based region, it's gone from Civo.com now. So please use`LON1`, `FRA1`, or `NYC1` for now - and once you use one of them you should be able to use `civo region ls` to find all regions.
