### ISSUE TITLE
typos / innacurate info in the help / command description

### ISSUE THREAD

**Issue by vbdockers** [civo/cli#78]
I discovered while using the cli that there are some inconsistencies with the information provided by the civo help while trying to set the current region:

civo region current --help
Output:
"**Set the current API key**"

Same thing appears in region_current.go: 

var regionCurrentCmd = &cobra.Command{
	Use:     "current [NAME]",
	Aliases: []string{"use", "default", "set"},
	**Short:   "Set the current API key"**,
	Args:    cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) ...

civo help region will also output:

...
Available commands:
**current  Set the current API key**

**Comment by alejandrojnm** [comment]
Hi @vbdockers thanks for this, is already fix, will be available in the next release
