### ISSUE TITLE
Creating volumes fails

### ISSUE THREAD

**Issue by andyjeffries** [civo/cli#85]
https://github.com/civo/kube100/issues/69

**Comment by saiyam1814** [comment]
For the resize, we can disable it for now.

**Comment by andyjeffries** [comment]
Huh, resize?

**Comment by zulh-civo** [comment]
@andyjeffries - that was Saiyam's response for my question [here](https://github.com/civo/cli/issues/120#issue-977618164). It supposed to be in that issue.
