### ISSUE TITLE
[Civo CLI] Listing of installed Apps

### ISSUE THREAD

**Issue by nunix** [civo/cli#88]
Dear team,

first of all, as my first issue, let me congratulate you for the exception work. The on-boarding is simply amazing.

With that said, while going through the KubeQuest, when using the `civo` cli, it could be nice to have the management of the Applications in one place.

Right now, there is two distinct places where we have different information about the Applications:
1. `civo kubernetes show <cluster name>`: will show information about the cluster and will list **only** the installed Applications
2. `civo kubernetes applications ls`: will show all the Marketplace applications and which can be installed

Now, the idea would be to either have a flag to show only the applications installed from the `applications` sub-command:
`civo kubernetes applications ls --installed`

Or have another field in the `ls` output with the cluster name(s) where the application is installed.

Hope this makes sense.

PS: this is an issue following a discussion on Slack 😄

**Comment by alejandrojnm** [comment]
I like the idea, but we have a problem using only the `civo kubernetes applications ls --installed` because we don't know where look, so we need say something like this `civo kubernetes applications ls --installed --cluster <MY-CLUSTER>` or `civo kubernetes applications ls <MY-CLUSTER> --installed`, @andyjeffries, what do you think?

**Comment by nunix** [comment]
yes, sorry, for the `--installed` you're totally right 😄 

or another idea would be to have the table output with the field "Cluster Name", so without `--cluster` or `<MY-CLUSTER>` is would be the equivalent to `--all`, but it might be overkill and keeping the command against 1 cluster only might be the best option 👍
