### ISSUE TITLE
Calling civo with illegal options and parameters returns exit status zero 

### ISSUE THREAD

**Issue by schmid-hanspeter** [civo/cli#90]
When invoking civo with an illegal combination of options and arguments (unknown or missing), the exit status is always zero.
Example
```
$ civo abc
Error: unknown command "abc" for "civo"
Run 'civo --help' for usage.
unknown command "abc" for "civo"
$ echo $?
0
```

Returning a non-zero exit status will make it easier to create robust scripting solutions that invoke civo.

Tested with version 0.7.17 on osx.

**Comment by schmid-hanspeter** [comment]
Thanks  @alejandrojnm ! Much appreciated.

**Comment by alejandrojnm** [comment]
I found a error in the last version I'm working to fixed now

**Comment by schmid-hanspeter** [comment]
I have just tested 0.7.18. Unfortunately, it seems broken in the places I tested. 
For example:
```
$ civo kube create
Create a new Kubernetes cluster

Usage:
  civo kubernetes create [flags]
..........
subcommand is required
$ echo $?
1
```
Same behaviour with a few other command I tested, like `civo template ls`.

**Comment by schmid-hanspeter** [comment]
We must have commented at the same time.

**Comment by alejandrojnm** [comment]
Hi @towerworks can you check again ??

**Comment by schmid-hanspeter** [comment]
Hi @alejandrojnm I have just run a few quick tests of version 0.7.19 and things look good!
