### ISSUE TITLE
Illegal cluster name in civo kube create reports 'Error: UnknownError'

### ISSUE THREAD

**Issue by schmid-hanspeter** [civo/cli#91]
Tested with civo 0.7.20 on osx.

I stumbled upon this by accident because of an error in my scripts. There seem to be some rules that govern what a legal cluster name should be but the error message is just a generic 'Error: UnknownError'. 

After some experimentation it looks to me like a cluster name must start with [a-zA-Z0-9] but that special characters are accepted after the first position.

Examples using the cli:
````
$ civo kube create %
Error: UnknownError

$ kube create 'a%b'
The cluster a%b (e06f9de8-d49e-45b3-8fd2-1e118fbd2fef) has been created
````

BTW, when creating a cluster with an illegal name (like %) through the web UI, the error message that comes back is "Timed out communicating with that region".

Worse yet, it is possible to create clusters with a name like 'aÇ' but since then nothing works anymore, not even ```civo kube ls``` (Error: InternalServerError: internal Server Error). ```civo kube delete 'aÇ'``` gives a stack trace 
````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16642c0]

goroutine 1 [running]:
github.com/civo/cli/cmd.glob..func69(0x1f83260, 0xc0001f2400, 0x1, 0x1)
        /home/runner/work/cli/cli/cmd/kubernetes_remove.go:53 +0xc80
github.com/spf13/cobra.(*Command).execute(0x1f83260, 0xc0001f23a0, 0x1, 0x1, 0x1f83260, 0xc0001f23a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1f86980, 0x1fa6520, 0x0, 0xc000056778)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/civo/cli/cmd.Execute()
        /home/runner/work/cli/cli/cmd/root.go:33 +0x31
main.main()
        /home/runner/work/cli/cli/main.go:23 +0x25
```

**Comment by alejandrojnm** [comment]
I will check this

**Comment by alejandrojnm** [comment]
This already fixed in the side of the API
