### ISSUE TITLE
Update on the documentation for removing default applications

### ISSUE THREAD

**Issue by alfonzjanfrithz** [civo/cli#93]
The following section on the documentation could be improved:

```
Starting a cluster without default applications

By default, `traefik` is bundled in with `k3s` to act as the ingress controller. If you want to set up a cluster without `traefik`, you can use the `remove-applications` option in the creation command to start a cluster without it:

civo kubernetes create --remove-applications=traefik --nodes=2 --wait
```

As `traefik` is not a valid applications and the cli seems to care about the case sensitivity. It is much better if we could let the user know that there is the following command available. 

`civo kubernetes applications ls | grep default`

I am happy to send pull request for this.

**Comment by kaihoffman** [comment]
I'm updating the documentation now, but I think it might be worth not having case sensitivity on the application naming, and it being worth discussing.

**Comment by alfonzjanfrithz** [comment]
brilliant thank you

> I'm updating the documentation now, but I think it might be worth not having case sensitivity on the application naming, and it being worth discussing.

brilliant, thanks!
