### ISSUE TITLE
Small bug in the show application command

### ISSUE THREAD

**Issue by zulh-civo** [civo/cli#94]
Hey @alejandrojnm,

I think I found a small bug. 

Where:

https://github.com/civo/cli/blob/master/cmd/kubernetes_app_show.go#L58-L61

What I think is wrong:

```go
if foundAPP {
    utility.Error("Sorry the app %s was not found in the cluster %s", args[0], args[1])
    os.Exit(1)
}
```

What I think is correct:

```go
if !foundAPP {
    utility.Error("Sorry the app %s was not found in the cluster %s", args[0], args[1])
    os.Exit(1)
}
```

**Comment by hazir12** [comment]
Hazir

**Comment by whtssub** [comment]
Hey, @zulh-civo I would like to begin my journey in contributing to civo through this simple issue first, I'd be glad if you could state any other changes associated with this issue that has to be solved.

**Comment by alejandrojnm** [comment]
Hi, @SubhasmitaSw this particular issue is already solved, but you are welcome to contribute to Civo if you found other issue

**Comment by SubhasmitaSw** [comment]
@alejandrojnm It would be great if you could redirect me to some beginner issue. Thanks,
