### ISSUE TITLE
Exporting Apps as part of JSON

### ISSUE THREAD

**Issue by kameshsampath** [civo/cli#96]
Right now the `civo k3s show my-cluster -o json` exports info API, K8s version, size, nodes. It will be nice to have the installed Apps also exported.

**Comment by kameshsampath** [comment]
CC: @andyjeffries

**Comment by alejandrojnm** [comment]
This is already fixed in the commit https://github.com/civo/cli/commit/4f6e53f87f7f779b256c46a23635afbd94d4815d
