### ISSUE TITLE
[Civo CLI] upper case output format no longer works 

### ISSUE THREAD

**Issue by DMajrekar** [civo/cli#97]
❯ ./civo version ; ./civo k3s ls --output custom --fields ID
Civo CLI v0.7.22
ID
ID
❯ ./civo version ; ./civo k3s ls --output custom --fields ID
Civo CLI v0.7.20
IMPORTANT: A newer version (v0.7.22) is available, please upgrade
c8ef21dc-9655-48dd-bd37-c16dcd0b646a
864d249a-d583-4774-8496-a0c1ff736019

**Comment by alejandrojnm** [comment]
Yes, all the fields were made lowercase to make them standard with the json output
